/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lk' at '9/15/16 2:06 PM' with Gradle 3.0
 *
 * @author lk, @date 9/15/16 2:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
